package com.zetcode.view;

import com.zetcode.configuration.Config;

import java.awt.*;
import javax.swing.*;

public class OptionsView extends JFrame {

    /**
     * Creates new form board
     */
    public OptionsView() {
        initComponents();
        setLocationRelativeTo(null);
        scr_number.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        // Variables declaration - do not modify
        JPanel sidebar = new JPanel();
        JLabel jLabel6 = new JLabel();
        btn_agentMovement = new javax.swing.JPanel();
        JLabel jLabel2 = new JLabel();
        JPanel btn_back = new JPanel();
        JLabel jLabel5 = new JLabel();
        btn_agentNumber = new javax.swing.JPanel();
        JLabel jLabel3 = new JLabel();
        JPanel jPanel3 = new JPanel();
        scr_movement = new javax.swing.JPanel();
        JLabel jLabel8 = new JLabel();
        JLabel jLabel9 = new JLabel();
        JLabel jLabel10 = new JLabel();
        JLabel jLabel11 = new JLabel();
        JLabel jLabel12 = new JLabel();
        ER_Slider = new javax.swing.JSlider();
        LF_Slider = new javax.swing.JSlider();
        EF_Slider = new javax.swing.JSlider();
        LR_Slider = new javax.swing.JSlider();
        LR_Value = new javax.swing.JTextField();
        ER_Value = new javax.swing.JTextField();
        LF_Value = new javax.swing.JTextField();
        EF_Value = new javax.swing.JTextField();
        agentMaxValue = new javax.swing.JTextField();
        agentRoomValue = new javax.swing.JTextField();
        JButton LR_Apply = new JButton();
        JButton ER_Apply = new JButton();
        JButton LF_Apply = new JButton();
        JButton EF_Apply = new JButton();
        JButton agentMovementApply = new JButton();
        scr_number = new javax.swing.JPanel();
        JLabel jLabel1 = new JLabel();
        JLabel jLabel4 = new JLabel();
        JLabel jLabel7 = new JLabel();
        JButton agentMaxApply = new JButton();
        JButton agentRoomApply = new JButton();
        JButton agentNumberApply = new JButton();

        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

        sidebar.setBackground(new java.awt.Color(54, 33, 89));
        sidebar.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("OPTIONS");

        btn_agentMovement.setBackground(new java.awt.Color(85, 55, 118));
        btn_agentMovement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_agentMovementMousePressed();
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AGENT MOVEMENT");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setInheritsPopupMenu(false);

        javax.swing.GroupLayout btn_agentMovementLayout = new javax.swing.GroupLayout(btn_agentMovement);
        btn_agentMovement.setLayout(btn_agentMovementLayout);
        btn_agentMovementLayout.setHorizontalGroup(
                btn_agentMovementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_agentMovementLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_agentMovementLayout.setVerticalGroup(
                btn_agentMovementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_agentMovementLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addContainerGap())
        );

        btn_back.setBackground(new java.awt.Color(64, 43, 100));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_backMousePressed();
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BACK");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setInheritsPopupMenu(false);

        javax.swing.GroupLayout btn_backLayout = new javax.swing.GroupLayout(btn_back);
        btn_back.setLayout(btn_backLayout);
        btn_backLayout.setHorizontalGroup(
                btn_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_backLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_backLayout.setVerticalGroup(
                btn_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_backLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addContainerGap())
        );

        btn_agentNumber.setBackground(new java.awt.Color(64, 43, 100));
        btn_agentNumber.setPreferredSize(new java.awt.Dimension(230, 48));
        btn_agentNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_agentNumberMousePressed();
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NUMBER OF AGENTS");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setInheritsPopupMenu(false);

        javax.swing.GroupLayout btn_agentNumberLayout = new javax.swing.GroupLayout(btn_agentNumber);
        btn_agentNumber.setLayout(btn_agentNumberLayout);
        btn_agentNumberLayout.setHorizontalGroup(
                btn_agentNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_agentNumberLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(45, Short.MAX_VALUE))
        );
        btn_agentNumberLayout.setVerticalGroup(
                btn_agentNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_agentNumberLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
                sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_agentMovement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(sidebarLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(sidebarLayout.createSequentialGroup()
                                .addComponent(btn_agentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
                sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidebarLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(btn_agentMovement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_agentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(640, 500));

        scr_movement.setPreferredSize(new java.awt.Dimension(640, 500));

        jLabel8.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Probability of agent");

        jLabel9.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 11)); // NOI18N
        jLabel9.setText("Entering the room:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 11)); // NOI18N
        jLabel10.setText("Leaving the room:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 11)); // NOI18N
        jLabel11.setText("Entering the floor:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 11)); // NOI18N
        jLabel12.setText("Leaving the floor:");

        LR_Value.setText(""+Config.getLR());
        ER_Value.setText(""+Config.getER());
        LF_Value.setText(""+Config.getLF());
        EF_Value.setText(""+Config.getEF());

        ER_Slider.setMajorTickSpacing(50);
        ER_Slider.setPaintLabels(true);
        ER_Slider.setPaintTicks(true);
        ER_Slider.setValue(Config.getER());
        ER_Slider.addChangeListener(this::ER_SliderStateChanged);

        LF_Slider.setMajorTickSpacing(50);
        LF_Slider.setPaintLabels(true);
        LF_Slider.setPaintTicks(true);
        LF_Slider.setToolTipText("");
        LF_Slider.setValue(Config.getLF());
        LF_Slider.addChangeListener(this::LF_SliderStateChanged);

        EF_Slider.setMajorTickSpacing(50);
        EF_Slider.setPaintLabels(true);
        EF_Slider.setPaintTicks(true);
        EF_Slider.setValue(Config.getEF());
        EF_Slider.addChangeListener(this::EF_SliderStateChanged);

        LR_Slider.setMajorTickSpacing(50);
        LR_Slider.setPaintLabels(true);
        LR_Slider.setPaintTicks(true);
        LR_Slider.setValue(Config.getLR());
        LR_Slider.addChangeListener(this::LR_SliderStateChanged);

        LR_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ER_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LF_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        EF_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LR_Apply.setText("Apply");
        LR_Apply.addActionListener(this::LR_ApplyActionPerformed);

        ER_Apply.setText("Apply");
        ER_Apply.addActionListener(this::ER_ApplyActionPerformed);

        LF_Apply.setText("Apply");
        LF_Apply.addActionListener(this::LF_ApplyActionPerformed);

        EF_Apply.setText("Apply");
        EF_Apply.addActionListener(this::EF_ApplyActionPerformed);

        agentMovementApply.setText("Apply all");
        agentMovementApply.addActionListener(this::agentMovementApplyActionPerformed);


        javax.swing.GroupLayout scr_movementLayout = new javax.swing.GroupLayout(scr_movement);
        scr_movement.setLayout(scr_movementLayout);
        scr_movementLayout.setHorizontalGroup(
                scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(scr_movementLayout.createSequentialGroup()
                                .addGroup(scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(scr_movementLayout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addGroup(scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(scr_movementLayout.createSequentialGroup()
                                                                .addComponent(ER_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(ER_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(scr_movementLayout.createSequentialGroup()
                                                                .addComponent(LR_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(LR_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(scr_movementLayout.createSequentialGroup()
                                                                .addComponent(LF_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(LF_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(scr_movementLayout.createSequentialGroup()
                                                                .addComponent(EF_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(EF_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(scr_movementLayout.createSequentialGroup()
                                                .addGap(227, 227, 227)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LR_Apply, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ER_Apply, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LF_Apply, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(EF_Apply, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap(63, Short.MAX_VALUE))
                        .addGroup(scr_movementLayout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(agentMovementApply)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scr_movementLayout.setVerticalGroup(
                scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(scr_movementLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addGroup(scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LR_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(LR_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LR_Apply)))
                                .addGap(18, 18, 18)
                                .addGroup(scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ER_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(ER_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ER_Apply)))
                                .addGap(18, 18, 18)
                                .addGroup(scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LF_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(LF_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LF_Apply)))
                                .addGap(18, 18, 18)
                                .addGroup(scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EF_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(scr_movementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(EF_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(EF_Apply)))
                                .addGap(40, 40, 40)
                                .addComponent(agentMovementApply)
                                .addContainerGap(58, Short.MAX_VALUE))
        );

        scr_number.setPreferredSize(new java.awt.Dimension(640, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Number of agents");

        jLabel4.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 11)); // NOI18N
        jLabel4.setText("In one room:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 11)); // NOI18N
        jLabel7.setText("In the floor (Max):");

        agentMaxValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        agentMaxValue.setText(""+Config.getAgentMax());

        agentRoomValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        agentRoomValue.setText(""+Config.getAgentRoom());

        agentMaxApply.setText("Apply");
        agentMaxApply.addActionListener(this::agentMaxApplyActionPerformed);

        agentRoomApply.setText("Apply");
        agentRoomApply.addActionListener(this::agentRoomApplyActionPerformed);

        agentNumberApply.setText("Apply all");
        agentNumberApply.addActionListener(this::agentNumberApplyActionPerformed);

        javax.swing.GroupLayout scr_numberLayout = new javax.swing.GroupLayout(scr_number);
        scr_number.setLayout(scr_numberLayout);
        scr_numberLayout.setHorizontalGroup(
                scr_numberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(scr_numberLayout.createSequentialGroup()
                                .addGroup(scr_numberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(scr_numberLayout.createSequentialGroup()
                                                .addGap(125, 125, 125)
                                                .addGroup(scr_numberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addGroup(scr_numberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(agentMaxValue, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                                        .addComponent(agentRoomValue))
                                                .addGap(82, 82, 82)
                                                .addGroup(scr_numberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(agentMaxApply)
                                                        .addComponent(agentRoomApply)))
                                        .addGroup(scr_numberLayout.createSequentialGroup()
                                                .addGap(228, 228, 228)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(scr_numberLayout.createSequentialGroup()
                                                .addGap(271, 271, 271)
                                                .addComponent(agentNumberApply)))
                                .addContainerGap(159, Short.MAX_VALUE))
        );
        scr_numberLayout.setVerticalGroup(
                scr_numberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(scr_numberLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addGroup(scr_numberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(agentMaxApply)
                                        .addComponent(agentMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(scr_numberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(scr_numberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(agentRoomValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(agentRoomApply)))
                                .addGap(66, 66, 66)
                                .addComponent(agentNumberApply)
                                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scr_movement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(scr_number, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scr_movement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(scr_number, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                                        .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btn_agentMovementMousePressed() {
        setColor(btn_agentMovement);
        resetColor(btn_agentNumber);
        scr_movement.setVisible(true);
        scr_number.setVisible(false);
    }

    private void btn_agentNumberMousePressed() {
        setColor(btn_agentNumber);
        resetColor(btn_agentMovement);
        scr_movement.setVisible(false);
        scr_number.setVisible(true);
    }

    private void btn_backMousePressed() {
        this.dispose();
    }

    private void LR_SliderStateChanged(javax.swing.event.ChangeEvent evt) {
        LR_Value.setText(""+LR_Slider.getValue());
        Config.setLR( this ,LR_Slider.getValue());
    }

    private void ER_SliderStateChanged(javax.swing.event.ChangeEvent evt) {
        ER_Value.setText(""+ER_Slider.getValue());
        Config.setER( this ,ER_Slider.getValue());
    }

    private void LF_SliderStateChanged(javax.swing.event.ChangeEvent evt) {
        LF_Value.setText(""+LF_Slider.getValue());
        Config.setLF( this ,LF_Slider.getValue());
    }

    private void EF_SliderStateChanged(javax.swing.event.ChangeEvent evt) {
        EF_Value.setText(""+EF_Slider.getValue());
        Config.setEF( this ,EF_Slider.getValue());
    }

    private void LR_ApplyActionPerformed(java.awt.event.ActionEvent evt) {
        LR_Slider.setValue(Integer.parseInt(LR_Value.getText()));
    }

    private void ER_ApplyActionPerformed(java.awt.event.ActionEvent evt) {
        ER_Slider.setValue(Integer.parseInt(ER_Value.getText()));
    }

    private void LF_ApplyActionPerformed(java.awt.event.ActionEvent evt) {
        LF_Slider.setValue(Integer.parseInt(LF_Value.getText()));
    }

    private void EF_ApplyActionPerformed(java.awt.event.ActionEvent evt) {
        EF_Slider.setValue(Integer.parseInt(EF_Value.getText()));
    }

    private void agentMovementApplyActionPerformed(java.awt.event.ActionEvent evt) {
        LR_Slider.setValue(Integer.parseInt(LR_Value.getText()));
        ER_Slider.setValue(Integer.parseInt(ER_Value.getText()));
        LF_Slider.setValue(Integer.parseInt(LF_Value.getText()));
        EF_Slider.setValue(Integer.parseInt(EF_Value.getText()));
    }

    private void agentMaxApplyActionPerformed(java.awt.event.ActionEvent evt) {
        Config.setAgentMax( this ,Integer.parseInt(agentMaxValue.getText()));
    }

    private void agentRoomApplyActionPerformed(java.awt.event.ActionEvent evt) {
        Config.setAgentRoom( this ,Integer.parseInt(agentRoomValue.getText()));
    }

    private void agentNumberApplyActionPerformed(java.awt.event.ActionEvent evt) {
      Config.setAgentMax( this ,Integer.parseInt(agentMaxValue.getText()));
      Config.setAgentRoom( this ,Integer.parseInt(agentRoomValue.getText()));
    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(85,55,118));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(64,43,100));
    }

    private javax.swing.JSlider EF_Slider;
    private javax.swing.JTextField EF_Value;
    private javax.swing.JSlider ER_Slider;
    private javax.swing.JTextField ER_Value;
    private javax.swing.JSlider LF_Slider;
    private javax.swing.JTextField LF_Value;
    private javax.swing.JSlider LR_Slider;
    private javax.swing.JTextField LR_Value;
    private javax.swing.JPanel btn_agentMovement;
    private javax.swing.JPanel btn_agentNumber;
    private javax.swing.JPanel scr_movement;
    private javax.swing.JPanel scr_number;
    private javax.swing.JTextField agentMaxValue;
    private javax.swing.JTextField agentRoomValue;
    // End of variables declaration
}
